---
- hosts: 172.31.45.22
  become: yes
  tasks: 
  #apt-get install git
   - include_tasks: mfile.yml
   - name: copy files into node side
     copy:
        src: mytestfile
        dest: /home/ubuntu/mytestfile
   - name: i want to install webserver on ansible nodes side
     apt:
      name: apache2
      state: present
   - name: i want copy index file  into ansible node side
     template:
       src:  mydynamicfile.j2
       dest: /var/www/html/index.html 