---
- hosts: all
  become: yes
  tasks: 
  #apt-get install git
  - name: install webserver on ansible nodes
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"

  - name: i want to start  webserver
    service:
     name: apache2
     state: started
    when: ansible_os_family=="Debian"

  - name: install webserver on  RedHat ansible nodes
    dnf:
     name: httpd
     state: present
    when: ansible_os_family=="RedHat"

  - name: i want to start RedHat  webserver
    service:
     name: httpd
     state: started
    when: ansible_os_family=="RedHat"